# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5206527f5561376ed74c1e84b4a484750f41bf198fc381042fd94895d714a0eb3ada0ea577d705ba803b2982b191fa62dbc4c5f7ac28d28ac2f90805befc5762

test:
  secret_key_base: d1107c4845c1e05a3058dc6e62b19f545b7fea55305d6c3e492d666abb5c16eb87cc5db6291cbb3d3f8a2dfc3b8f186195ce975118f5c4f1f743ed7de4502025

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
